// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3zYWQ6-SlVXY8tPyUCWul2DNwUvsieZo',
    appId: '1:552817073225:web:0dad504a847d51dfe2f398',
    messagingSenderId: '552817073225',
    projectId: 'aka-chat-4e550',
    authDomain: 'aka-chat-4e550.firebaseapp.com',
    storageBucket: 'aka-chat-4e550.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHNh9Qssu1nx8VNzzQ8WgM3yY3H5hunOc',
    appId: '1:552817073225:android:ef828df41fc10a29e2f398',
    messagingSenderId: '552817073225',
    projectId: 'aka-chat-4e550',
    storageBucket: 'aka-chat-4e550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQff5nG1HyuMR8TZhhJt-_gJyH6krizFA',
    appId: '1:552817073225:ios:6c9b46cf408a0d79e2f398',
    messagingSenderId: '552817073225',
    projectId: 'aka-chat-4e550',
    storageBucket: 'aka-chat-4e550.appspot.com',
    iosBundleId: 'com.example.akaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQff5nG1HyuMR8TZhhJt-_gJyH6krizFA',
    appId: '1:552817073225:ios:3ad201e3f1f782ace2f398',
    messagingSenderId: '552817073225',
    projectId: 'aka-chat-4e550',
    storageBucket: 'aka-chat-4e550.appspot.com',
    iosBundleId: 'com.example.akaChat.RunnerTests',
  );
}
